# Generated by Django 3.0.5 on 2022-06-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220617_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='biaSach',
            field=models.ImageField(default=None, upload_to='sach'),
        ),
    ]
