# Generated by Django 3.0.5 on 2022-06-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220622_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='biaSach',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
